[package]
name = "advent-2021"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"
cached = "0.26.2"
rand = "0.6.5"